# Generated by Django 5.1.4 on 2025-02-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='networth_countries',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='networth_currencies',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='networth_holders',
        ),
        migrations.AddField(
            model_name='preference',
            name='networth',
            field=models.JSONField(default=dict),
        ),
    ]
