# Generated by Django 5.1.4 on 2025-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_preference_networth_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='savings_holders',
            field=models.JSONField(default=list),
        ),
    ]
