# Generated by Django 5.1.4 on 2025-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_preference_savings_holders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='networth',
        ),
        migrations.AddField(
            model_name='preference',
            name='business_holders',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='fixed_asset_holders',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='investment_holders',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='stock_holders',
            field=models.JSONField(default=list),
        ),
    ]
