# Generated by Django 5.1.4 on 2026-05-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_preference_networth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='email_report_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preference',
            name='forecast_period_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='preference',
            name='forecast_rate_business',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='preference',
            name='forecast_rate_fixed_asset',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='preference',
            name='forecast_rate_stock',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
