# Generated by Django 5.1.4 on 2025-02-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='networth_options',
            field=models.JSONField(default=dict),
        ),
    ]
