# Generated by Django 5.1.4 on 2025-01-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bonuspoint',
            name='unique_active_record',
        ),
    ]
