# Generated by Django 5.1.4 on 2025-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore', '0002_remove_bonuspoint_unique_active_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiatework',
            name='name',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
    ]
