from datetime import datetime


def wrap_html_for_export(body_html: str, title: str) -> str:
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: "Segoe UI", Arial, sans-serif; max-width: 740px; margin: 40px auto; color: #0f172a; line-height: 1.7; }}
    header {{ background: linear-gradient(140deg,#0f172a,#1e293b,#334155); color:#f8fafc; border-radius: 12px; padding: 28px 32px; margin-bottom: 32px; }}
    header h1 {{ margin: 0 0 6px; font-size: 1.3rem; }}
    header p  {{ margin: 0; font-size: 0.82rem; color: #94a3b8; }}
    .content {{ padding: 0 4px; }}
    h1,h2,h3 {{ color: #1e293b; }}
    code {{ background:#f1f5f9; border:1px solid #dbe3ee; padding:0.1em 0.35em; border-radius:4px; font-size:0.88em; }}
    pre  {{ background:#f1f5f9; border:1px solid #dbe3ee; padding:1rem; border-radius:8px; overflow:auto; }}
    table {{ width:100%; border-collapse:collapse; margin:1rem 0; }}
    th,td {{ border:1px solid #dbe3ee; padding:8px 12px; text-align:left; }}
    th {{ background:#f8fafc; font-weight:700; }}
    footer {{ margin-top:40px; padding-top:16px; border-top:1px solid #dbe3ee; font-size:0.78rem; color:#94a3b8; text-align:center; }}
  </style>
</head>
<body>
  <header>
    <h1>{title}</h1>
    <p>Nwokoro Financial Advisor &bull; {timestamp}</p>
  </header>
  <div class="content">{body_html}</div>
  <footer>Generated by Nwokoro AI Advisor &mdash; ai.uzonwokoro.com/advisor</footer>
</body>
</html>"""
