# Generated by Django 5.1.4 on 2025-02-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='holder',
            field=models.CharField(max_length=50),
        ),
    ]
