# Generated by Django 5.1.4 on 2025-01-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='category',
            field=models.CharField(default='GIC', max_length=30),
        ),
        migrations.AddField(
            model_name='saving',
            name='category',
            field=models.CharField(default='TFSA', max_length=30),
        ),
    ]
