# Generated by Django 5.1.4 on 2025-03-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0002_alter_saving_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
