# Generated by Django 5.1.4 on 2025-01-19 05:12

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0003_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='principal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saving',
            name='value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
    ]
