# Generated by Django 5.1.4 on 2025-01-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0004_alter_investment_principal_alter_saving_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
