# Generated by Django 5.1.4 on 2025-06-27 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0005_injectfund_rewardfund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedfund',
            name='host_country',
        ),
        migrations.RemoveField(
            model_name='borrowedfund',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='borrowedfund',
            name='repayment_amount',
        ),
        migrations.RemoveField(
            model_name='borrowedfund',
            name='repayment_amount_currency',
        ),
        migrations.RemoveField(
            model_name='borrowedfund',
            name='repayment_period',
        ),
        migrations.RemoveField(
            model_name='borrowedfund',
            name='repayment_start_date',
        ),
        migrations.RemoveField(
            model_name='borrowedfund',
            name='settled_amount',
        ),
        migrations.RemoveField(
            model_name='borrowedfund',
            name='settled_amount_currency',
        ),
        migrations.AddField(
            model_name='borrowedfund',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='borrowedfund',
            name='savings_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='networth.saving'),
        ),
        migrations.AlterField(
            model_name='borrowedfund',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
