# Generated by Django 5.1.4 on 2025-06-27 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0006_remove_borrowedfund_host_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedfund',
            name='terminal_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowedfund',
            name='savings_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networth.saving'),
        ),
    ]
