# Generated by Django 5.1.4 on 2025-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0007_borrowedfund_terminal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedfund',
            name='host_country',
            field=models.CharField(default='NG', max_length=2),
        ),
    ]
