# Generated by Django 5.1.4 on 2025-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0008_borrowedfund_host_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedfund',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
