# Generated by Django 5.1.4 on 2025-07-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0009_borrowedfund_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
