# Generated by Django 5.1.4 on 2025-01-31 18:05

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0010_business_businesstransaction_fixedasset_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('borrowed_amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='CAD', editable=False, max_length=3)),
                ('borrowed_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('settlement_amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='CAD', editable=False, max_length=3)),
                ('settlement_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('repayment_amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='CAD', editable=False, max_length=3, null=True)),
                ('repayment_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('repayment_start_date', models.DateField(blank=True, null=True)),
                ('repayment_period', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('settled_amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='CAD', editable=False, max_length=3)),
                ('settled_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('host_country', models.CharField(max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedFundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='CAD', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(max_length=2)),
                ('borrowed_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_fund_transactions', to='networth.borrowedfund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_borrowed_fund_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
