# Generated by Django 5.1.4 on 2025-12-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0011_rent_fixedasset_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
