# Generated by Django 5.1.4 on 2025-02-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0012_financialdata_networth_by_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdata',
            name='exchange_rate',
            field=models.JSONField(null=True),
        ),
    ]
