# Generated by Django 5.1.4 on 2026-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0014_infonote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infonote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='infodesk/'),
        ),
    ]
