# Generated by Django 5.1.4 on 2026-09-25 21:46

import datetime
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networth', '0015_alter_infonote_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250)),
                ('reviewed_on', models.DateField(default=datetime.date.today)),
                ('code', models.CharField(help_text='ISO country code, or WORLD for the global factor', max_length=5, unique=True)),
                ('sovereign', models.FloatField(default=0, help_text='Sovereign/political stress loss (0-1)')),
                ('convertibility', models.FloatField(default=0, help_text="Stress loss from funds that can't be moved or converted out (0-1)")),
                ('at_war', models.BooleanField(default=False, help_text='War or total collapse: forces this layer to 1.0')),
            ],
            options={
                'verbose_name_plural': 'country risks',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250)),
                ('reviewed_on', models.DateField(default=datetime.date.today)),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('stress_floor', models.FloatField(default=0, help_text='Minimum 1-year stress loss vs USD from long-run history (0-1)')),
            ],
            options={
                'verbose_name_plural': 'currency risks',
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250)),
                ('reviewed_on', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('aliases', models.CharField(blank=True, help_text='Other holder names for this institution, comma separated', max_length=250)),
                ('failure_probability', models.FloatField(help_text='Chance of failure in a bad year (0-1)')),
                ('loss_given_failure', models.FloatField(help_text='Share of uninsured value lost if it fails (0-1)')),
                ('insured_limit_currency', djmoney.models.fields.CurrencyField(choices=[('CAD', 'Canadian Dollar'), ('NGN', 'Nigerian Naira'), ('USD', 'US Dollar')], default='CAD', editable=False, max_length=3, null=True)),
                ('insured_limit', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Deposit insurance cover per depositor; blank if none', max_digits=14, null=True)),
            ],
            options={
                'verbose_name_plural': 'institution risks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetTypeRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250)),
                ('reviewed_on', models.DateField(default=datetime.date.today)),
                ('asset_class', models.CharField(choices=[('saving', 'Saving'), ('investment', 'Investment'), ('stock', 'Stock'), ('business', 'Business'), ('fixed_asset', 'Fixed Asset')], max_length=20)),
                ('category', models.CharField(blank=True, help_text='Blank = default for the asset class', max_length=30)),
                ('stress', models.FloatField(help_text='Bad-year loss of the instrument itself (0-1)')),
            ],
            options={
                'verbose_name_plural': 'asset type risks',
                'ordering': ['asset_class', 'category'],
                'unique_together': {('asset_class', 'category')},
            },
        ),
    ]
